//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.28 at 04:56:51 PM CET 
//


package rs.ac.uns.ftn.agenti;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.agenti package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.agenti
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeletePhotoResponse }
     * 
     */
    public DeletePhotoResponse createDeletePhotoResponse() {
        return new DeletePhotoResponse();
    }

    /**
     * Create an instance of {@link GetPhotosForSmestajReuqest }
     * 
     */
    public GetPhotosForSmestajReuqest createGetPhotosForSmestajReuqest() {
        return new GetPhotosForSmestajReuqest();
    }

    /**
     * Create an instance of {@link CreatePhotoResponse }
     * 
     */
    public CreatePhotoResponse createCreatePhotoResponse() {
        return new CreatePhotoResponse();
    }

    /**
     * Create an instance of {@link PhotoWS }
     * 
     */
    public PhotoWS createPhotoWS() {
        return new PhotoWS();
    }

    /**
     * Create an instance of {@link GetPhotosForSmestajResponse }
     * 
     */
    public GetPhotosForSmestajResponse createGetPhotosForSmestajResponse() {
        return new GetPhotosForSmestajResponse();
    }

    /**
     * Create an instance of {@link CreateSmestajResponse }
     * 
     */
    public CreateSmestajResponse createCreateSmestajResponse() {
        return new CreateSmestajResponse();
    }

    /**
     * Create an instance of {@link SmestajWS }
     * 
     */
    public SmestajWS createSmestajWS() {
        return new SmestajWS();
    }

    /**
     * Create an instance of {@link LoginAgentResponse }
     * 
     */
    public LoginAgentResponse createLoginAgentResponse() {
        return new LoginAgentResponse();
    }

    /**
     * Create an instance of {@link UserWS }
     * 
     */
    public UserWS createUserWS() {
        return new UserWS();
    }

    /**
     * Create an instance of {@link GetSmestajForUserRequest }
     * 
     */
    public GetSmestajForUserRequest createGetSmestajForUserRequest() {
        return new GetSmestajForUserRequest();
    }

    /**
     * Create an instance of {@link DeletePhotoRequest }
     * 
     */
    public DeletePhotoRequest createDeletePhotoRequest() {
        return new DeletePhotoRequest();
    }

    /**
     * Create an instance of {@link CreateSmestajIdReponse }
     * 
     */
    public CreateSmestajIdReponse createCreateSmestajIdReponse() {
        return new CreateSmestajIdReponse();
    }

    /**
     * Create an instance of {@link LoginAgentRequest }
     * 
     */
    public LoginAgentRequest createLoginAgentRequest() {
        return new LoginAgentRequest();
    }

    /**
     * Create an instance of {@link GetSmestajForUserResponse }
     * 
     */
    public GetSmestajForUserResponse createGetSmestajForUserResponse() {
        return new GetSmestajForUserResponse();
    }

    /**
     * Create an instance of {@link CreatePhotoRequest }
     * 
     */
    public CreatePhotoRequest createCreatePhotoRequest() {
        return new CreatePhotoRequest();
    }

    /**
     * Create an instance of {@link CreateSmestajIdRequest }
     * 
     */
    public CreateSmestajIdRequest createCreateSmestajIdRequest() {
        return new CreateSmestajIdRequest();
    }

    /**
     * Create an instance of {@link CreateSmestajRequest }
     * 
     */
    public CreateSmestajRequest createCreateSmestajRequest() {
        return new CreateSmestajRequest();
    }

}
